// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRPGList.Data;

#nullable disable

namespace MyRPGList.Migrations;

[DbContext(typeof(MyRpgListDbContext))]
partial class MyRpgListDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("MyRPGList.Models.Game", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .HasColumnType("longtext");

                b.Property<string>("Developer")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.HasKey("Id");

                b.ToTable("Games");
            });
#pragma warning restore 612, 618
    }
}
